### ISSUE TITLE
{{did-update}} fails for Ember 3.23 beta

### ISSUE THREAD

**Issue by simonihmig** [buschtoens/ember-render-helpers#282]
Does not call the callback, in Ember 3.23.0-beta and 3.24.0-canary.

Reproduction: `ember try:one ember-beta`

This is not visible in Travis yet, as CI is even failing earlier: #281 (see all those pending dependabot PRs)

**Comment by boris-petrov** [comment]
I just hit this in 3.23.0 final. @buschtoens - any ideas?

**Comment by buschtoens** [comment]
Thanks for pinging! This seems to have slipped past my attention, sorry.

I'll try to look into it today.

**Comment by buschtoens** [comment]
Published as [`v0.2.0`](https://github.com/buschtoens/ember-render-helpers/releases/tag/v0.2.0). 🚀 

Thank you for your contributions! And sorry that I left you hanging for so long :/
